name       : xorg-driver-video-radeon
version    : 7.10.0
release    : 30
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-ati-7.10.0.tar.gz : 4592bf0a7cdc3c6f40b52cffea15e32e2ef832ac18835c1875e5143cd91db68d
license    : GPL-2.0+
component  : xorg.driver
summary    : Open source Radeon Video Driver
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(xext)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(dri3proto)
optimize   : no-bind-now
description: |
    The Xorg ATI Driver package contains the X.Org Video Driver for ATI Radeon video cards including all chipsets ranging from R100 to R900 and the newer RAxx chipsets.
setup      : |
    %configure  CFLAGS="$CFLAGS -O3" CXXFLAGS="$CXXFLAGS -O3"
build      : |
    %make
install    : |
    %make_install
    install -D COPYING %installroot%/usr/share/doc/xorg-driver-video-radeon/COPYING
