name        : xorg-driver-video-radeon
version     : 7.7.0
release     : 12
source      :
    - http://xorg.freedesktop.org/releases/individual/driver/xf86-video-ati-7.7.0.tar.bz2 : 844d1c577b145c90dc8ef027678f0c27f554363f782cd696a3aea26415b2c1c3
license     : GPL-2.0+
componentn  : xorg.driver
summary     : Open source Radeon Video Driver
builddeps   :
    - pkgconfig(xorg-server)
    - pkgconfig(xext)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(dri3proto)
description : |
    The Xorg ATI Driver package contains the X.Org Video Driver for ATI Radeon video cards including all chipsets ranging from R100 to R900 and the newer RAxx chipsets.
setup      : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    export CXXFLAGS="${CXXFLAGS/-Wl,-z,now/}"
    %configure
build      : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    export CXXFLAGS="${CXXFLAGS/-Wl,-z,now/}"
    %make
install    : |
    export CFLAGS="${CFLAGS/-Wl,-z,now/}"
    export LDFLAGS="${LDFLAGS/-Wl,-z,now/}"
    export CXXFLAGS="${CXXFLAGS/-Wl,-z,now/}"
    %make_install
    install -D COPYING %installroot%/usr/share/doc/xorg-driver-video-radeon/COPYING
