name       : xorg-driver-video-radeon
version    : 19.0.1
release    : 41
source     :
    - https://www.x.org/releases/individual/driver/xf86-video-ati-19.0.1.tar.bz2 : 5cb6015d8664546ad1311bc9c363d7bc41ebf60e7046ceb44dd38e5b707961b0
license    : MIT
component  : xorg.driver
summary    : Open source Radeon Video Driver
description: |
    The Xorg ATI Driver package contains the X.Org Video Driver for ATI Radeon video cards including all chipsets ranging from R100 to R900 and the newer RAxx chipsets.
builddeps  :
    - pkgconfig(xorg-server)
    - pkgconfig(xext)
    - pkgconfig(resourceproto)
    - pkgconfig(scrnsaverproto)
    - pkgconfig(dri3proto)
optimize   :
    - no-bind-now
    - no-symbolic
setup      : |
    %configure CFLAGS="$CFLAGS -O3" CXXFLAGS="$CXXFLAGS -O3"
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 COPYING $installdir/usr/share/doc/xorg-driver-video-radeon/COPYING
